[package]
name = "ten"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bench]]
name = "ten_bench"
harness = false

[dependencies]
lazy_static = "1.4.0"
rayon = "1.5.1"

[dev-dependencies]
bencher = "0.1.4"
